[build]
  functions = "functions"
  publish = "dist"
  command = "npm run build netlify"

[[plugins]]
  package = "@netlify/plugin-lighthouse"


[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200